= TP Inicial - Aplicación de la Inteligencia Artificial
version 1.0 - 15 Marzo, 2024: 
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

== Integrantes

* Franco Disabato <francodisabatobook@gmail.com>
* Suarez Matias <matiassuarez265@gmail.com>
* Ayza Diego <diegoayza82@gmail.com>

== 

* Juan Carlos Monteros <jcmonteros@campus.ungs.edu.ar>
* Evelin Aragon <eve_aragon@hotmail.com>

== Objetivos

* Investigar y documentar los conceptos de IA en la vida diaria, Onboarding Digital, su importancia y normativas vigentes. 
* Implementar un chatbot que interactue con el usuario y le pida la informacion necesaria para confirmar su identidad y/o responder las preguntas que pueda tener sobre el proceso de Onboarding.


== Documentacion

A continuacion se documenta la investigacion realizada acerca de Aplicaciones de IA, Onboarding Digital y Normativas Existentes

=== Aplicaciones de la IA

==== Medicina
Busca la eficiencia de los equipos de diagnósticos médicos así se podrán descartar errores
humanos en el análisis de datos y se reducirían costos en investigación. Algunos avances en esta
materia ya se están viendo al usar programas como el IBM Watson y los chatbots para que
interactúe con el paciente realizando una serie de preguntas que le permiten formular una hipótesis
del posible estado de salud el paciente o para realizar análisis de seguimiento. 

==== Educación
Su aplicación en esta rama seria vital debido a que con sistemas capaces de evaluar a cada
estudiante trazando un plan de trabajo con sus necesidades, permitiría al maestro enfocarse
directamente a suplir las verdaderas deficiencias de cada estudiante. Además, lo que hace el machine
learning es dotar la educación del recurso faltante que para muchos es la calidad. 

==== Construcción
En este campo ha dado grandes resultados debido a que antes la mayoría de los sistemas en las
fábricas eran manipulados por los seres humanos esto se deducía en horarios de trabajo cortos y
poca producción, si a eso le sumamos tal vez las peligrosas actividades que se debían realizar en
algunas fábricas ya que esto reducía la eficiencia. Lo que cambiaría con la llegada del machine
learning en combinación con la robótica, lo cual hoy en día ha permitido la automatización de
grandes fábricas generando una mayor rentabilidad y una mayor eficiencia. 

==== Finanzas
En este sistema fue una de sus primeras apariciones debido a que muchas industrias necesitaban
una plataforma que fuese intuitiva y que permitiera a sus usuarios revisar y verificar sus trámites y
transacciones. Mediante programas que recopilaban información de los clientes de muchas entidades 
financieras, incluso el software IBM Watson hoy en día es de vital importancia en mercados como 
el de Wall Street ya que realiza la mayoría de las operaciones. 

==== La Robótica
A nivel de esta industria el impacto del machine learning es sorprendente tanto en la actualidad
como en sus predicciones a futuro. Donde industrias como Honda con su robot Asimo, han logrado
demostrar como un organismo robótico puede suplir a un hombre en el cumplimiento de labores
que hoy en día se creían complejas para las maquinas.

=== Onboarding Digital

Es el proceso de adquirir un nuevo cliente para una nueva compañia, tipicamente usando un telefono celular. El principal proposito del Onboarding digital es verificar la identidad del nuevo usuario para asegurarse de que dicha persona es quien dice ser. Para verificar la indentidad de un usuario digital y remotamente se utilizan datos biometricos faciales y tecnologia de "deteccion de vida", convinados con la capacidad de procesar documentos de identidad digitalmente.
La deteccion de vida es una tecnica en donde un algoritmo detecta con seguridad si una muestra biometrica proviene de una representacion falsa(foto quieta) o si es un ser humano vivo. La muestra biometrica es una foto facial tomada por el usuario. El algoritmo es capaz de diferenciar una persona viva de otro tipo de ataques, por ejemplo, mascaras, fotos o videos pre-grabados.


=== Normativas Existentes

==== Aprendizaje supervisado
En el aprendizaje supervisado, la máquina se enseña con el ejemplo. De este modo, el operador proporciona al algoritmo de aprendizaje automático un conjunto de datos conocidos que incluye las entradas y salidas deseadas, y el algoritmo debe encontrar un método para determinar cómo llegar a esas entradas y salidas.
Mientras el operador conoce las respuestas correctas al problema, el algoritmo identifica patrones en los datos, aprende de las observaciones y hace predicciones. El algoritmo realiza predicciones y es corregido por el operador, y este proceso sigue hasta que el algoritmo alcanza un alto nivel de precisión y rendimiento.

==== Aprendizaje sin supervisión
El algoritmo de aprendizaje automático estudia los datos para identificar patrones. No hay una clave de respuesta o un operador humano para proporcionar instrucción. En cambio, la máquina determina las correlaciones y las relaciones mediante el análisis de los datos disponibles.
En un proceso de aprendizaje no supervisado, se deja que el algoritmo de aprendizaje automático interprete grandes conjuntos de datos y dirija esos datos en consecuencia. Así, el algoritmo intenta organizar esos datos de alguna manera para describir su estructura. Esto podría significar la necesidad de agrupar los datos en grupos u organizarlos de manera que se vean más organizados. A medida que evalúa más datos, su capacidad para tomar decisiones sobre los mismos mejora gradualmente y se vuelve más refinada.

==== Aprendizaje por refuerzo
El aprendizaje por refuerzo se centra en los procesos de aprendizajes reglamentados, en los que se proporcionan algoritmos de aprendizaje automáticos con un conjunto de acciones, parámetros y valores finales.
Al definir las reglas, el algoritmo de aprendizaje automático intenta explorar diferentes opciones y posibilidades, monitorizando y evaluando cada resultado para determinar cuál es el óptimo.
En consecuencia, este sistema enseña la máquina a través del proceso de ensayo y error. Aprende de experiencias pasadas y comienza a adaptar su enfoque en respuesta a la situación para lograr el mejor resultado posible.


== Herramientas a Utilizar

* Github como controlador de fuentes y desarrollar en paralelo.
* Python como lenguaje de programacion y scikit-learn como biblioteca de herramientas de machine learning. 

== Referencias

https://www.innovatrics.com/glossary/digital-onboarding/